org: chengyilin

app: deploy-test
service: deploy-test
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  api:
    handler: server/handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline