org: chengyilin

app: deploy-test
service: deploy-test
frameworkVersion: "3"

provider:
    name: aws
    runtime: nodejs14.x
    apiGateway:
        binaryMediaTypes:
            - "application/pdf"

plugins:
    - serverless-offline
    - serverless-webpack

package:
    individually: true

custom:
    serverless-offline:
        location: .webpack/service
    webpack:
        webpackConfig: "webpack.config.js"
        includeModules: true
        packager: "npm"
        packagerOptions: "./package-lock.json"

functions:
    generate-pdf:
        handler: src/handler.handler
        events:
            - httpApi: "*"
